billy_online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
   
    #securing admin pane. record login attempts by duplicating the admin panel
    # path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    #we change the admin/ to secured_billy so that can not access admin pane
    path('mulopwe/', admin.site.urls),
    #my site urls
    path('', views.home, name= 'home'),
    path('store/', include('store.urls')),
    path('cart/', include('cart.urls')),
    path('accounts/', include('accounts.urls')),
    # ORDERS
    path('orders/', include('orders.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .import views

urlpatterns = [
    path('cart', views.cart, name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name="add_cart"),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name="remove_cart"),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name="remove_cart_item"),
    path('checkout/', views.checkout, name="checkout"),
]

store/urls.py
from django.urls import path



from . import views

urlpatterns = [
  
    path('', views.store, name='store'),
    #desplay products by category
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    #this the way we can access the single product, 
    path('category/<slug:category_slug>/<product_slug>/', views.product_detail, name='product_detail'),
    path('submit_review/<int:product_id>/', views.submit_review, name="submit_review"),
    path('search/', views.search, name='search'),
    
]

store/models.py
from django.db import models
from django.forms import ValidationError
from django.urls import reverse
from accounts.models import Account
from django.db.models import Avg, Count


class PCategory(models.Model):
    category_name = models.CharField(max_length=50, unique=True)
    slug          = models.SlugField(max_length=100, unique=True)
    description   = models.TextField(max_length=225)
    image         = models.ImageField(upload_to='categories', blank=True)
    
    #in order to fix the way category wil appear in admin panel will be Categorys that is not what you want . to fix u can use meta
    class Meta:
        verbose_name = 'pcategory'
        verbose_name_plural = 'pcategories'
        
    def get_url(self):
        return reverse('products_by_category', args=[self.slug])
        
        
    def __str__(self):
        return self.category_name

class Product(models.Model):
    product_name       = models.CharField(max_length=200, unique=True)
    slug               = models.SlugField(max_length=200, unique=True)
    description        = models.TextField(max_length=500, blank=True)
    price              = models.IntegerField()
    image              = models.ImageField(upload_to='products', blank=True)
    stock              = models.IntegerField()
    is_available       = models.BooleanField(default=True) 
    category           = models.ForeignKey(PCategory, on_delete=models.CASCADE)

    created_date       = models.DateTimeField(auto_now_add=True)
    modefied_date      = models.DateTimeField(auto_now=True)
    
    def clean(self):
        if not self.image:
            raise ValidationError('Each product must have an associated image.')

   
    def get_url(self):
        # this url will help us to get single product url, if you click any product or name it takes you to that  product detail by using refering product name
        return reverse('product_detail', args=[self.category.slug, self.slug]) #this one takes 2 argument the first one is category slug and the second is the product slug
    
    def __str__(self):
        return self.product_name

    #===========calculating the rating average=========================
    def averageReview(self):
            reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(average=Avg('rating'))
            return reviews['average'] or 0.0

       
    #===========calculating count review=========================
    def countReview(self):
            reviews = ReviewRating.objects.filter(product=self, status=True).aggregate(count=Count('id'))
            return reviews['count'] or 0
    
    

from django.db import models

variation_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
)

class VariationManager(models.Manager):
    def colors(self):
        return self.filter(variation_category='color', is_active=True)
    
    def sizes(self):
        return self.filter(variation_category='size', is_active=True)
    
class Variation(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation_category = models.CharField(max_length=100, choices=variation_category_choice)
    variation_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    createe_date = models.DateTimeField(auto_now=True)
    
    objects = VariationManager()
    
    def __str__(self):
        return self.variation_value


    
    
# #revieew and rating system we need the models
# #after creating the models you need to create a review form.py file in store app
class ReviewRating(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    subject = models.CharField(max_length=100, blank=True)
    review = models.TextField(max_length=500, blank = True)
    rating = models.FloatField()
    ip = models.CharField(max_length=20, blank=True)
    status = models.BooleanField(default=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.subject

#==============product gallary======================================start here
class ProductGallary(models.Model):

    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    image = models.ImageField(upload_to="store/products", max_length=255)

    def __str__(self):

        return self. product.product_name


    class Meta:

        verbose_name_plural = 'product gallary'

store/forms.py
from .models import ReviewRating

from django import forms

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewRating
        fields = ['subject', 'review', 'rating']

store/views.py
from django.shortcuts import render, get_object_or_404

from cart.models import CartItem, Cart
from orders.models import OrderProduct
from .forms import ReviewForm
from .models import Product, PCategory, ProductGallary, ReviewRating
from cart.views import _cart_id
from django.core.paginator import PageNotAnInteger,EmptyPage, Paginator
from django.contrib import messages
from django.shortcuts import redirect

def store(request, category_slug=None):
    categories = None
    products = Product.objects.filter(is_available=True)

    if category_slug:
        categories = get_object_or_404(PCategory, slug=category_slug)
        products = products.filter(category=categories)

    # Paginator setup
    paginator = Paginator(products, 6)  # Default to 6 products per page
    page = request.GET.get('page')
    paged_products = paginator.get_page(page)

    context = {
        'products': paged_products,
        'categories': categories,
    }

    return render(request, 'store/store.html', context)

#=============================single product start here===========================================================
def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug) #in order to get single product we need to access the category name in the product model and slu name in category models thats why we use category__slug
        #this will check if the product added to cart  or not
        in_cart = CartItem.objects.filter(cart__cart_id=_cart_id(request), product=single_product).exists()

    except Exception as e:
        raise e

    orderproduct = None
    if request.user.is_authenticated:

        try:
            orderproduct = OrderProduct.objects.filter(user=request.user, product_id=single_product.id).exists()
        except OrderProduct.DoesNotExist:
            orderproduct = None
    
    #get  the review ==============here==============================
    reviews = ReviewRating.objects.filter(product_id=single_product.id, status=True)
    #get product gallery==============here==============================
    product_gallery = ProductGallary.objects.filter(product_id=single_product.id)
    
    context = {
        'single_product': single_product,
        'in_cart': in_cart,
        'product_gallery': product_gallery, 
        'reviews': reviews,
        'orderproduct': orderproduct,
    }

    return render(request, 'store/product_detail.html', context)
#================search view functions start here===================================
def submit_review(request, product_id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        try:
            reviews = ReviewRating.objects.get(user__id=request.user.id, product__id=product_id)
            form = ReviewForm(request.POST, instance=reviews)
            form.save()
            messages.success(request, 'Thank you! Your review has been updated.')
            return redirect(url)
        except ReviewRating.DoesNotExist:
            form = ReviewForm(request.POST)
            if form.is_valid():
                data = ReviewRating()
                data.subject = form.cleaned_data['subject']
                data.rating = form.cleaned_data['rating']
                data.review = form.cleaned_data['review']
                data.ip = request.META.get('REMOTE_ADDR')
                data.product_id = product_id
                data.user_id = request.user.id
                data.save()
                #this message you need to go the product detail to implement the the messsa
                
                messages.success(request, 'Thank you! Your review has been submitted.')
                return redirect(url)
#================search view functions start here===================================
from django.db.models import Q
def search(request):
    products = []
    product_count = 0  # Initialize product_count
 
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
     
        if keyword:
            # Filter products based on keyword
            products = Product.objects.order_by('-created_date').filter(
                Q(description__icontains=keyword) | Q(product_name__icontains=keyword)
            )
            product_count = products.count()
          
    
    context = {
        'products': products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context)

templates/store/checkout.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="row">
            <aside class="col-lg-6 ">
                <div class="card ">
                    <div class="card-body" >
                        <h4 class="card-title mb-4">Billing Address</h4>
                        <form action="{% url 'place_order' %}" method="POST">

                            {% csrf_token %}
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">First Name</label>
                                    <input type="text" name="first_name" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Last Name</label>
                                    <input type="text" name="last_name" class="form-control" required>
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Email</label>
                                        <input type="text" name="email" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Phone Number</label>
                                    <input type="text" name="phone" class="form-control" required>
                                </div>
                            </div> 
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">Address line 1</label>
                                        <input type="text" name="address_line_1" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">Address Line 2</labell>
                                    <input type="text" name="address_line_2" class="form-control" >
                                </div>
                            </div> 
                            <div class="form-row">
                                <div class="col form-group">
                                    <label for="">City</label>
                                        <input type="text" name="city" class="form-control" required>
                                </div>
                                <div class="col form-group">
                                    <label for="">State</label>
                                    <input type="text" name="state" class="form-control" required >
                                </div>
                                <div class="col form-group">
                                    <label for="">Country</label>
                                    <input type="text" name="country" class="form-control" required>
                                </div>
                            </div>    
                                <div class="form-row">
                                    <label for="">Order Note
                                    <textarea name="order_note" rows="2" class="form-control"></textarea>
                                    </label>
                                </div>
                        
                     
                      
                    </div>
                </div>
              
            </aside> <!-- col.// -->
            <aside class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        
                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                            {% for cart_item in cart_items %}   
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{{ cart_item.product.image.url }}" class="img-sm"></div>
                                        <figcaption class="info">
                                            <!--thi cart_item.product.get_url will bring us back to that  product detail-->
                                            <a href="{{ cart_item.product.get_url }}" class="title text-dark">{{ cart_item.product.product_name }}</a>
                                            <p class="text-muted small">
                                                {% if cart_item.variation.all %}

                                                  {% for item in cart_item.variation.all %}
                                                   {{ item.variation_category | capfirst}} : {{ item.variation_value | capfirst}}<br>
                                                  {% endfor %}
                                                {% endif %}
                                            </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td> 
                                   
                                   <label for="">{{ cart_item.quantity }}</label> 
                                </td>
                                <td> 
                                    <div class="price-wrap"> 
                                        <!--//this will calculate the Quantity of all total-->
                                        <var class="price">$ {{ cart_item.sub_total }}</var> <!--//but this one is for total for all you have to create function for sub total-->
                                        <small class="text-muted"> $ {{ cart_item.product.price}} each </small> <!--//this will show the single product price-->
                                    </div> <!-- price-wrap .// -->
                                </td>
                               
                                
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div> <!-- card.// -->
                     
                       
                        
                       
                        <div style="display: flex; justify-content: center;">
                            <button type="submit" class="btn btn-primary" style="width: 150px;"> Please Order <i class="fas fa-sign-in-alt" style="color: white;"></i> </button>
                       
                          
                        </div>
                        
                        <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->
            </form>   
            </aside> <!-- col.// -->
        </div> <!-- row.// -->
        
        <!-- ============================ COMPONENT 1 END .// ================================= -->
    </div> <!-- container .//  -->
</section>

  
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}

templates/store/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="section-content padding-y bg">
  <div class="container ">

  <!-- Product Display -->
  <div class="card shadow">
    <div class="row no-gutters">
      <aside class="col-md-6">
        <article class="gallery-wrap"> 
          <div class="img-big-wrap mainImage">
            <img src="{{single_product.image.url}}" style="max-width: 100%; height: auto; display: block; margin: 0 auto;">
          </div>
        </article>
        
        <ul class="thumb" style="padding: 0; margin: 0 auto; display: flex; flex-wrap: wrap; justify-content: center;">
          {% for i in product_gallery %}
            <li style="list-style: none; margin: 10px;">
              <a href="{{ i.image.url }}" class="thumbnail-link" target="mainImage">
                <img src="{{ i.image.url }}" alt="product image" style="width: 80px; height: 80px; border: 1px solid grey; object-fit: cover;">
              </a>
            </li>
          {% endfor %}
        </ul>
      </aside>
      <main class="col-md-6 border-left">

        <form action="{% url 'add_cart' single_product.id %}" method="POST">
          {% csrf_token %}
          <article class="content-body">

            <h2 class="title">{{ single_product.product_name }}</h2>
            <div class="rating-star">
              <span>
                <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
                <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
                <span>{{single_product.countReview}} reviews</span>
                </span>
            </div>

            <div class="mb-3"> 
              <var class="price h4">$ {{ single_product.price }}</var> 
            </div> 

            <p>{{ single_product.description }}.</p>
            
            <hr>
            <!-- <div class="row">
              <div class="item-option-select">
                <h6>Choose Color</h6>
                <div class="btn-group btn-group-sm btn-group-toggle form-control" data-toggle="buttons" >
                  {% for i in single_product.variation_set.colors %}
                    <label class="btn btn-light" value="{{ i.variation_value}}">
                      <input type="radio" name="radio_color" value="{{ i.variation_value }}" required> 
                      {{ i.variation_value }}
                    </label>
                  {% empty %}
                    <p class="text-muted">No colors available</p>
                  {% endfor %}
                </div> 
              </div>
            </div>  -->

            <div class="row">
              <div class="item-option-select">
                <h6>Choose Color</h6>
                <select name="color" class="form-control" required>
                  <option value="" disabled selected>Select</option>
                  {% for i in single_product.variation_set.colors %}
                    <option value="{{i.variation_value }}">{{i.variation_value }}</option>
                  {% endfor %}
                </select>
              </div>
            </div> 
            
        
            
            <hr>
            {% if single_product.stock <= 0 %}
              <h4 class="text-danger"> Out of stock </h4>
            {% else %}
              <button type="submit" class="btn btn-primary"> <span class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i>  </button>
            {% endif %}
          </article>
        </form>

      </main>
    </div>
  </div>

  <br>

  <!-- Review Section -->
  <div class="row shadow">
    <div class="col-md-9">

      <form action="{% url 'submit_review' single_product.id %}" method="POST">
        {% csrf_token %}
        <h5>Write your Review</h5>
        <div>
          <label>How would you rate this Product?</label>
          <br>
          <div class="rate">
            <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
            <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
            <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
            <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
            <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
            <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
            <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
            <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
            <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
            <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
          </div>

          <br>
          Review Title:
          <input type="text" class="form-control shadow" name="subject">
          <br>
          Review:
          <textarea name="review" rows="4" class="form-control shadow"></textarea>
          <br>
          {% if user.is_authenticated %}
            {% if orderproduct %}
              <input type="submit" value="submit Review " class="btn btn-primary">
            {% else %}
              <p>You must buy this product to post a review.</p>
            {% endif %}
          {% else %}
            <p>You must be logged in to post a review. <span><a href="{% url 'login' %}">Login now</a></span></p>
          {% endif %}
        </div>
        {% include 'includes/alert.html' %}
      </form>

      <br>

      <header class="section-heading">
        <h3>Customer Reviews</h3>  
        <span>Average</span> 
        <div class="rating-star">
          <span>
            <i class="fa fa-star{% if single_product.averageReview < 0.5 %}-o{% elif single_product.averageReview >= 0.5 and single_product.averageReview < 1 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 1.5 %}-o{% elif single_product.averageReview >= 1.5 and single_product.averageReview < 2 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 2.5 %}-o{% elif single_product.averageReview >= 2.5 and single_product.averageReview < 3 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 3.5 %}-o{% elif single_product.averageReview >= 3.5 and single_product.averageReview < 4 %}-half-o {% endif %}" aria-hidden="true"></i>
            <i class="fa fa-star{% if single_product.averageReview < 4.5 %}-o{% elif single_product.averageReview >= 4.5 and single_product.averageReview < 5 %}-half-o {% endif %}" aria-hidden="true"></i>
            <span>{{single_product.countReview}} reviews</span>
            </span>
        </div>
      </header>

      {% for review in reviews %}
        <article class="box mb-3">
          <div class="icontext w-100">
            <img src="{% static 'images/billy1.jpg'%}" class="img-xs icon rounded-circle">
            <div class="text">
              <span class="date text-muted float-md-right">{{ review.updated_at }}</span>  
              <h6 class="mb-1">{{ review.user.full_name }}</h6>
              <div class="rating-star">
								<span>
									<i class="fa fa-star{% if review.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
									<i class="fa fa-star{% if review.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
								</span>
							</div>
            </div>
          </div>
          <div class="mt-3">
            <h4>{{ review.subject }}</h4>
            <p>{{ review.review }}</p>	
          </div>
        </article>
      {% endfor %}

    </div> <!-- col.// -->
  </div> <!-- row.// -->

  </div> <!-- container .//  -->
</section>

{% endblock %}

templates/store/product_not_found.html
<h1>page not found</h1>